sudo: false # use Travis container based infrastructure

language: python

env:
  - MOCK=1 TOXENV=py26
  - MOCK=1 TOXENV=py27
  - MOCK=1 TOXENV=py33
  - MOCK=1 TOXENV=py34
  - MOCK=1 TOXENV=pypy
  - MOCK=1 TOXENV=pypy3

install:
  - pip install tox

before_script:
  - git clone https://github.com/sstephenson/bats.git /tmp/bats
  - mkdir -p /tmp/local
  - bash /tmp/bats/install.sh /tmp/local
  - export PATH=$PATH:/tmp/local/bin

script:
  - tox

notifications:
  email:
    on_success: never
